# Generated by Django 6.0.3 on 2026-03-10 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='subsceibed_date',
            new_name='subscribed_date',
        ),
    ]
