# Generated by Django 6.0.3 on 2026-03-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_rename_subsceibed_date_subscriber_subscribed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='open_count',
            field=models.IntegerField(default=0),
        ),
    ]
